version: "3.8"

services:
  backend:
    image: maven:3.9-eclipse-temurin-21
    container_name: task-manager-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    env_file:
      - .env.cloud
    command: mvn spring-boot:run